2022-09-13 11:50:53,376 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 11:50:58,942 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 11:51:01,458 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 11:51:06,863 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 11:51:45,298 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 14:53:24,290 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 14:53:39,465 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 14:53:50,936 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 14:56:52,105 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 15:10:26,777 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 15:15:35,591 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:05:58,061 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:06:23,334 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:06:44,893 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:06:49,771 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:39:45,771 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:40:41,132 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:44:42,417 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:44:48,345 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:45:00,880 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:46:13,329 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:46:18,094 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:46:46,194 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:46:53,893 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:52:19,427 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:52:24,867 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:52:28,603 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:53:16,869 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:53:26,938 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:53:31,147 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:53:35,154 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:57:40,546 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:57:45,471 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:59:03,746 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:59:07,860 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 17:59:11,651 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 18:12:22,325 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 18:12:27,435 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 18:12:31,413 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 18:20:25,262 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 18:20:29,822 INFO: PFV2 startup [in /home/opc/flask/pfv2/app/__init__.py:36]
2022-09-13 18:22:08,929 ERROR: Exception on /login [GET] [in /usr/local/lib64/python3.6/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/opc/flask/pfv2/app/routes.py", line 25, in login
    form = LoginForm()
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/form.py", line 73, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 286, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 127, in process
    field.process(formdata, data, extra_filters=field_extra_filters)
  File "/usr/local/lib/python3.6/site-packages/wtforms/csrf/core.py", line 44, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/csrf.py", line 148, in generate_csrf_token
    secret_key=self.meta.csrf_secret, token_key=self.meta.csrf_field_name
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/csrf.py", line 40, in generate_csrf
    message="A secret key is required to use CSRF.",
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/csrf.py", line 136, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2022-09-13 18:22:12,479 ERROR: Exception on /register [GET] [in /usr/local/lib64/python3.6/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/opc/flask/pfv2/app/routes.py", line 55, in register
    form = RegistrationForm()
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/form.py", line 73, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 286, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 127, in process
    field.process(formdata, data, extra_filters=field_extra_filters)
  File "/usr/local/lib/python3.6/site-packages/wtforms/csrf/core.py", line 44, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/csrf.py", line 148, in generate_csrf_token
    secret_key=self.meta.csrf_secret, token_key=self.meta.csrf_field_name
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/csrf.py", line 40, in generate_csrf
    message="A secret key is required to use CSRF.",
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/csrf.py", line 136, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2022-09-13 18:22:24,428 ERROR: Exception on /register [GET] [in /usr/local/lib64/python3.6/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/opc/flask/pfv2/app/routes.py", line 55, in register
    form = RegistrationForm()
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/form.py", line 73, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 286, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 127, in process
    field.process(formdata, data, extra_filters=field_extra_filters)
  File "/usr/local/lib/python3.6/site-packages/wtforms/csrf/core.py", line 44, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/csrf.py", line 148, in generate_csrf_token
    secret_key=self.meta.csrf_secret, token_key=self.meta.csrf_field_name
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/csrf.py", line 40, in generate_csrf
    message="A secret key is required to use CSRF.",
  File "/usr/local/lib64/python3.6/site-packages/flask_wtf/csrf.py", line 136, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2022-09-15 12:12:21,734 INFO: PFV2 startup [in /home/opc/simple-login/pfv2/app/__init__.py:36]
2022-09-15 12:14:39,290 INFO: PFV2 startup [in /home/opc/simple-login/pfv2/app/__init__.py:36]
